/**
 * Normalize errors generated by mongoose.
 * Takes errors generated by mongoose and extracts data for creating a simple error list
 * each of them are structured with a title and a detail message.
 * @param errors errors generate by 
 * @returns simple error messages list
 */
exports.normalizeError = function (errors)
{
    // normalized errors
    const normalizedErrors = [];
    // prepare simple errors
    for (const property in errors)
    {
        if (errors.hasOwnProperty(property))
        {
            // add error to normalized errors list.
            normalizedErrors.push({ title: property, detail: errors[property].message });
        }
    }
    // return errors
    return normalizedErrors;
} // normalizeError